config/routes.rb
Rails.application.routes.draw do
  root 'messages#index'
  resources :messages , except: [:index, :new]

end

app/models/message.rb
class Message < ActiveRecord::Base
    # 名前は必須かつ20文字以内
    validates :name , length: { maximum: 20 } , presence: true
    # 内容は必須入力かつ2文字以上30文字以下
    validates :body , length: { minimum: 2 , maximum: 30 } , presence: true
    # 年齢は必須入力かつ０文字以上の整数値
    validates :age , numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:edit, :update, :destroy]
  def index
    @message = Message.new
    #Messageを全て取得する。
    @messages = Message.all
  end
  
  def create
    @message = Message.new(message_params)
    if @message.save
      redirect_to root_path , notice: 'メッセージを保存しました'
    else
      # メッセージが保存できなかった時
      @messages = Message.all
      flash.now[:alert] = "メッセージの保存に失敗しました。"
      render 'index'
    end
    
    def edit
    end
    
    def update
      if @message.update(message_params)
        # 保存に成功した場合はトップページへリダイレクト
        redirect_to root_path , notice: 'メッセージを編集しました'
      else
        # 保存に失敗した場合は編集画面へ戻す
        render 'edit'
      end
    end
    
    def destroy
      @message.destroy
      redirect_to root_path, notice: 'メッセージを削除しました'
    end
  end
  
  private
  def message_params
    params.require(:message).permit(:name, :body, :age)
  end
  
  def set_message
    @message = Message.find(params[:id])
  end
  #ここまで
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MessageBoard</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <style>
    body{
      width:100%;
      background-color:#f5f5dc;
    }
    
     .navbar {
      width:100%;
      padding:20px 15px;
      font-family: arial black;
    }
    
    .navbar-brand{
      font-size:40px;
    }
    
    .nav-pills {
      padding: 20px 0 20px 50px;
      font-size: 30px;
    }
    
    .panel {
      font-size: 20px;
    }
    
    .container {
      margin:20px 50px;
      padding:20px 0;
      font-size: 40px;
    }
    
    .label_name {
      margin:10px 0;
    }
    
    .form_group {
      font-size: 20px;
    }
    
    .field_with_errors #inputname {
      width:200px;
    }

    #inputmain {
      font-size: 20px;
    }

    .field_with_errors #inputage {
      width:100px;
    }
    
    .btn {
      width:100%;
      margin: 30px 0;
      margin-left:auto;
      font-size: 20px;
    }
    
  </style>
</head>
<body>
  <nav class="navbar">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="container-fluid navbar-brand" href="https://shoday10-message-board.herokuapp.com/">Message Board</a>
      </div>
    </div>
  </nav>
    <ul class="nav nav-pills">
      <li role="presentation" class="active"><a href="https://shoday10-message-board.herokuapp.com/">Messages</a></li>
      <li role="presentation"><a href="#">Profile</a></li>
    </ul>
  <div class="container-fluid">
    <% if notice %>
      <div class="alert alert-info">
        <%= notice %>
      </div>
    <% end %>
    
    <%= yield %>
  </div>
</body>
</html>

app/views/messages/_form.html.erb
<%= form_for @message, html: {class: 'form-horizontal'} do |f| %>
    <% if @message.errors.present? %>
        <div class="alert alert-danger">
            <%= alert %>
            <ul>
                <% @message.errors.full_messages.each do |full_message| %>
                <li>
                    <%= full_message %>
                </li>
                <% end %> 
            </ul>
        </div>
    <% end %>
    <div class="form_group">
        <label for="input_name" class="col-ms-2 control-label">名前:</label><br>
        <%= f.text_field :name, id: "inputname", class: "col-ms-10 form-fontrol", size: "23" %>
    </div>
    <div class="form_group">
        <label for="input_age" class="col-ms-2 control-label">年齢:</label><br>
        <%= f.text_field :age, id: "inputage", class: "col-ms-10 form-fontrol", size: "10" %>
    </div>
    <div class="form_group">
        <label for="input_main" class="col-ms-2 control-label">内容:</label>
        <%= f.text_area :body, id: "inputmain", class: "col-ms-10 form-control", size: "10x10" %>
    </div>
    <div class="form_group">
        <div class="conrainer-fluid">
        <%= f.submit "投稿", class: "btn btn-sm btn-primary" %>
        </div>
    </div>
<% end %>

app/views/messages/edit.html.erb
<h1>メッセージの編集</h1>

<%= render 'form' %>

app/views/messages/index.html.erb
<div class="panel panel-default">
    <div class="panel-heading">
        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
        メッセージ一覧
    </div>
    
    <div class="panel-body">
        <% @messages.each do |message| %>
        <div class="label_name">
            <span class="label label-info"><%= message.name %></span>
                (
                <%= message.age %>
                歳)
        </div>
                <br>
                <%= message.body %>
                (<%= link_to "edit" , edit_message_path(message) %>
                 <%= link_to "destroy" , message , method: :delete, data: { confirm: '削除してもよろしいですか？'} %>
                )
            <br>
            <hr>
        <% end %>
    </div>
</div>

<% #部分テンプレートを読み込んでいる %>
<%= render 'form' %>